services:
  neo4j:
    image: neo4j:2025.09.0
    container_name: mcpneo4j-docker
    restart: unless-stopped
    ports:
      - "7474:7474" # Neo4j Browser (HTTP)
      - "7473:7473" # Bloom (HTTPS)
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/mcpneo4j
      - NEO4J_PLUGINS=["apoc","apoc-extended","graph-data-science","genai"]
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./plugins:/plugins
      - ./import:/import